services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: unless-stopped
    user: root
    ports:
      - "8080:8080"
    volumes:
      - /mnt/jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /home/ju_admin/deploy/portfolio-web:/opt/env:ro
    environment:
      - JAVA_OPTS=-Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=86400
